### PR TITLE
fix: resolve validation errors (fixes #163)

### LINKED ISSUE #163: Validation Errors - Duplicate classes and others
## Describe the bug

The following [validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwecount.netlify.com%2F)

## To Reproduce

Steps to reproduce the behaviour:

1. Inspect the [We count website](https://wecount.netlify.com/)
2. Run a validator, for example "Validity"
3. Go to console and errors will appear
4. See errors

## Expected behaviour
No errors in the console after running a validator

## Screenshots

https://html5.validator.nu/?doc=https%3A%2F%2Fwecount.netlify.com%2F

## Additional context

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwecount.netlify.com%2F

### PR DESCRIPTION
**Pull request by greatislander**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run dev` and reviewing affected routes
* [x] This pull request has been built by running `npm run generate` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Resolves validation errors identified in #163.

## Steps to test

1. Validate deploy preview: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-165--wecount.netlify.com%2F

**Expected behavior:** Errors are resolved.

## Additional information

Not applicable.

## Related issues

Resolve #163.

### CODE REVIEW

**Comment by cindyli** [comment]
Thanks for the fix, @greatislander. 

Could you take the chance to fix the warning on the views post page too? 

One example: https://html5.validator.nu/?doc=https%3A%2F%2Fdeploy-preview-165--wecount.netlify.com%2Fviews%2Fcontinuing-our-work-during-covid-19&showsource=yes

Thanks.

File: pages/index.vue [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <template>
-	<article>
+	<div>
```
Comment (TeddTech) [inline pages/index.vue:2]: because of this change. The article in `_layout.scss` associated with this element should be changed from article to div as well. 

As of now the white background for the article is not showing *see homepage*

Comment (greatislander) [reply pages/index.vue:2]: Resolved in a3b91a3.
