### PR TITLE
fix: remove bootstrap vue

### LINKED ISSUE #49: Remove Bootstrap

### PR DESCRIPTION
**Pull request by TeddTech**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run dev` and reviewing affected routes
* [x] This pull request has been built by running `npm run generate` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

Removes Bootstrap Vue dependency.

## Steps to test

1. Visit all routes.

**Expected behavior:** All routes work without the use of Bootstrap Vue components.

## Additional information

Not applicable.

## Related issues

- Resolves #49.

### CODE REVIEW

**Comment by TeddTech** [comment]
> Please remove the dependency from package.json as well.

boostrap has been removed as a dependency

**Comment by greatislander** [comment]
@TeddTech once #68 is merged, please complete this pull request (including removing the pagination component).

**Comment by TeddTech** [comment]
false alarm

File: pages/tag/_query/index.vue [hunk 1]
```diff
@@ -1,11 +1,11 @@
 <template>
-	<b-row align-h="center">
+	<div align-h="center">
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: Without bootstrap-vue, `align-h` doesn't do anything. Please remove it throughout the components.

File: pages/tag/_query/index.vue [hunk 2]
```diff
@@ -1,11 +1,11 @@
...
 		<div id="container">
 			<h1 id="title">
 				<b>TAG: "{{ searchQuery }}"</b>
 			</h1>
-			<b-row v-for="row in groupedPosts" :key="row.id">
-				<b-col id="api-content" v-for="x in row" :key="x.id">
+			<div v-for="row in groupedPosts" :key="row.id">
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: This should be a `NewsGrid` with `NewsItems` like the news page.

File: pages/tag/_query/index.vue [hunk 3]
```diff
@@ -21,10 +21,10 @@
 						:slug="x.slug"
 						style="width: 50%"
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: As per @jobara, remove inline styles.

File: pages/news-and-views/_slug/index.vue [hunk 4]
```diff
@@ -1,5 +1,5 @@
 <template>
-	<b-row align-h="center">
+	<div align-h="center">
```
Comment (greatislander) [inline pages/news-and-views/_slug/index.vue]: This template should use the `Article` component.

File: pages/tag/_query/index.vue [hunk 5]
```diff
@@ -1,11 +1,11 @@
 <template>
-	<b-row align-h="center">
+	<div align-h="center">
 		<div id="container">
 			<h1 id="title">
 				<b>TAG: "{{ searchQuery }}"</b>
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: Remove `<b>` tags.

File: pages/news-and-views/_slug/index.vue [hunk 6]
```diff
@@ -1,5 +1,5 @@
 <template>
-	<b-row align-h="center">
+	<div>
 		<div id="container">
 			<h1 id="title">
 				<b>{{ Title }}</b>
```
Comment (greatislander) [inline pages/news-and-views/_slug/index.vue]: Remove this `<b>` tag.

File: pages/search/_query/index.vue [hunk 7]
```diff
@@ -1,31 +1,11 @@
...
-						:slug="x.slug"
-						style="width: 50%"
-					/>
-				</b-col>
-			</b-row>
-		</div>
-	</b-row>
+	<div class="container">
+		<h1 id="title">
+			SEARCH: "{{ searchQuery }}"
```
Comment (greatislander) [inline pages/search/_query/index.vue]: - Don't put "Search" in uppercase; if it needs to be uppercased we can do that with CSS.
- Use [curly quotes](https://practicaltypography.com/straight-and-curly-quotes.html) around the search query.

File: pages/search/_query/index.vue [hunk 8]
```diff
@@ -1,31 +1,11 @@
...
+		</h1>
+		<p>We found {{ pagesPosts.length }} results for your search.</p>
+		<NewsGrid :postList="filterdBlogs" />
```
Comment (greatislander) [inline pages/search/_query/index.vue]: A couple comments: `filterdBlogs` has a typo in it. Also, you've searched both posts and pages below but you're only passing the post results to the NewsGrid component here.

File: pages/search/_query/index.vue [hunk 9]
```diff
@@ -39,10 +19,6 @@ export default {
 	},
 	computed: {
 		searchQuery () {
-			// const myRegexp = /rch\?s=(.*)/
-			// const currentPath = this.$nuxt.$route.fullPath
-			// const match = myRegexp.exec(currentPath)
-			// return match[1]
 			return decodeURIComponent(this.$nuxt.$route.fullPath.match(/rch\?s=(.*)/)[1])
 		},
 		filterdBlogs () {
```
Comment (greatislander) [inline pages/search/_query/index.vue]: I suggest renaming this to `foundPosts`.

Comment (greatislander) [reply pages/search/_query/index.vue]: Also, rename `filteredPages` to `foundPages`, and rename `pagesPosts` to `searchResults`.

Comment (greatislander) [reply pages/search/_query/index.vue]: Also, remove `groupedPosts` and the `lodash` import as it's not being used.

File: pages/search/_query/index.vue (hunk 8 above)
Comment (greatislander) [inline pages/search/_query/index.vue]: The `NewsGrid` component has not been imported.

File: pages/tag/_query/index.vue [hunk 10]
```diff
@@ -1,36 +1,18 @@
 <template>
-	<b-row align-h="center">
-		<div id="container">
+	<div class="container">
 			<h1 id="title">
-				<b>TAG: "{{ searchQuery }}"</b>
+				TAG: "{{ searchQuery }}"
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: - Don't put "TAG" in uppercase; if it needs to be uppercased we can do that with CSS.
- Use [curly quotes](https://practicaltypography.com/straight-and-curly-quotes.html) around the search query.

File: pages/tag/_query/index.vue [hunk 11]
```diff
@@ -1,36 +1,18 @@
...
-			</b-row>
-		</div>
-	</b-row>
+		<NewsGrid :postList="filterdBlogs" />
+	</div>
 </template>
 
 <script>
+import NewsGrid from "~/components/NewsGrid"
 import _ from "lodash"
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: Remove `groupedPosts` and this `lodash` import as it's not used.

File: pages/tag/_query/index.vue [hunk 12]
```diff
@@ -1,36 +1,18 @@
...
-						:title="x.title"
-						:date="x.date"
-						:slug="x.slug"
-						style="width: 50%"
-					/>
-				</b-col>
-			</b-row>
-		</div>
-	</b-row>
+		<NewsGrid :postList="filterdBlogs" />
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: Rename `filterdBlogs` to `foundPosts`.

File: pages/news-and-views/_slug/index.vue [hunk 13]
```diff
@@ -1,5 +1,5 @@
 <template>
-	<b-row align-h="center">
+	<div>
 		<div id="container">
 			<h1 id="title">
```
Comment (greatislander) [inline pages/news-and-views/_slug/index.vue]: Any reason you didn't use the `Article` component here as we discussed?

Comment (greatislander) [reply pages/news-and-views/_slug/index.vue]: Also, the social media toolbar is still here.

File: pages/search/_query/index.vue (hunk 8 above)
Comment (TeddTech) [reply pages/search/_query/index.vue]: in the original we count site both pages and posts showed up in search and only posts in tags

File: pages/news-and-views/_slug/index.vue [hunk 14]
```diff
@@ -1,122 +1,10 @@
 <template>
-	<b-row align-h="center">
-		<div id="container">
+		<Article id="container">
```
Comment (greatislander) [inline pages/news-and-views/_slug/index.vue]: @TeddTech You aren't actually using the Article component here. It should look like this: https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/master/pages/index.vue#L2

File: pages/search/_query/index.vue [hunk 15]
```diff
@@ -1,65 +1,39 @@
...
-						:slug="x.slug"
-						style="width: 50%"
-					/>
-				</b-col>
-			</b-row>
-		</div>
-	</b-row>
+	<div class="container">
+		<h1 id="title">
+			search: “{{ searchQuery }}”
```
Comment (greatislander) [inline pages/search/_query/index.vue]: Should be a capital `s`.

File: pages/tag/_query/index.vue [hunk 16]
```diff
@@ -1,36 +1,17 @@
 <template>
-	<b-row align-h="center">
-		<div id="container">
+	<div class="container">
 			<h1 id="title">
-				<b>TAG: "{{ searchQuery }}"</b>
+				tag: “{{ searchQuery }}”
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: Should be a capital `t`.

File: pages/tag/_query/index.vue [hunk 17]
```diff
@@ -1,36 +1,17 @@
...
-						:title="x.title"
-						:date="x.date"
-						:slug="x.slug"
-						style="width: 50%"
-					/>
-				</b-col>
-			</b-row>
-		</div>
-	</b-row>
+		<NewsGrid :postList="foundPages" />
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: There are no tags on pages. This should be `foundPosts`.

File: pages/tag/_query/index.vue [hunk 18]
```diff
@@ -40,13 +21,15 @@ export default {
...
 		},
-		filterdBlogs () {
+		foundPosts () {
 			return this.$store.state.posts.filter((blog) => {
 				return blog.title.concat(" ", blog.content, " ", blog.tags.join(" ")).toLowerCase().match(this.searchQuery.toLowerCase())
 			})
 		},
-		groupedPosts () {
-			return _.chunk(this.filterdBlogs, 2)
+		foundPages () {
```
Comment (greatislander) [inline pages/tag/_query/index.vue]: There are no tags on pages. This method is not needed.

File: components/PostArticle.vue [hunk 19]
```diff
@@ -0,0 +1,50 @@
...
+					class="svg-icon"
+					aria-hidden="true"
+					role="img"
+					focusable="false"
+					tabindex="-1"
+					xmlns="http://www.w3.org/2000/svg"
+					width="18"
+					height="18"
+					viewBox="0 0 18 18"
+				><path fill="" d="M15.4496399,8.42490555 L8.66109799,1.63636364 L1.63636364,1.63636364 L1.63636364,8.66081885 L8.42522727,15.44178 C8.57869221,15.5954158 8.78693789,15.6817418 9.00409091,15.6817418 C9.22124393,15.6817418 9.42948961,15.5954158 9.58327627,15.4414581 L15.4486339,9.57610048 C15.7651495,9.25692435 15.7649133,8.74206554 15.4496399,8.42490555 Z M16.6084423,10.7304545 L10.7406818,16.59822 C10.280287,17.0591273 9.65554997,17.3181054 9.00409091,17.3181054 C8.35263185,17.3181054 7.72789481,17.0591273 7.26815877,16.5988788 L0.239976954,9.57887876 C0.0863319284,9.4254126 0,9.21716044 0,9 L0,0.818181818 C0,0.366312477 0.366312477,0 0.818181818,0 L9,0 C9.21699531,0 9.42510306,0.0862010512 9.57854191,0.239639906 L16.6084423,7.26954545 C17.5601275,8.22691012 17.5601275,9.77308988 16.6084423,10.7304545 Z M5,6 C4.44771525,6 4,5.55228475 4,5 C4,4.44771525 4.44771525,4 5,4 C5.55228475,4 6,4.44771525 6,5 C6,5.55228475 5.55228475,6 5,6 Z" /></svg>							</span>
```
Comment (greatislander) [inline components/PostArticle.vue]: @TeddTech This is a design element that isn't reflected in the designs, so I'd suggest removing it for now.

File: components/PostArticle.vue [hunk 20]
```diff
@@ -0,0 +1,50 @@
...
+			<span v-for="(t, index) in tags" :key="index">
+				<nuxt-link v-if="(index+1)===tags.length" :to="{ path: '/tag', query: { s: t }}">{{ t }} </nuxt-link>
+				<nuxt-link v-else :to="{ path: '/tag', query: { s: t }}">{{ t }},  </nuxt-link>
```
Comment (greatislander) [inline components/PostArticle.vue]: The comma should not be in the link text, as it will cause screen readers to behave strangely (including an unneeded pause at the end of the link). I'd suggest leaving the separator out; the designs may call for something different. Instead, make all the `<nuxt-link>` elements the same.
