### PR TITLE
Missing prop type (resolve #10)

### LINKED ISSUE #10: Fix: missing prop types (Post.vue)
## Describe the bug

When running in dev mode:

```
wecount.inclusivedesign.ca/components/Post.vue
  48:10  warning  Prop "picture" should define at least its type  vue/require-prop-types
  48:21  warning  Prop "title" should define at least its type    vue/require-prop-types
  48:30  warning  Prop "date" should define at least its type     vue/require-prop-types
  48:38  warning  Prop "slug" should define at least its type     vue/require-prop-types

✖ 4 problems (0 errors, 4 warnings)
```

## To Reproduce

1.`npm run dev`
2. Examine CLI console.

## Expected behavior

No warning.

## Additional context

cc: @TeddTech

### PR DESCRIPTION
**Pull request by TeddTech**
This PR resolves issue #10

### CODE REVIEW

File: components/Post.vue [hunk 1]
```diff
@@ -45,7 +45,21 @@
...
 	// Pages have no media attached to them so when they render they are imageless
-	props: ["picture", "title", "date", "slug"]
+	props: {
+		picture: {
+			type: Object,
+			default: () => "https://wecount.inclusivedesign.ca/wp-content/uploads/2019/10/We-Count-logos_colour-and-bw-01.png"
+		},
+		title: {
+			type: String,
+			default: "We Count Default"
```
Comment (greatislander) [inline components/Post.vue]: If a post doesn't have a title, I'd suggest providing something more meaningful (e.g. 'Untitled Post').

File: components/Post.vue [hunk 2]
```diff
@@ -45,7 +45,21 @@
...
+		},
+		date: Date,
+		slug: {
+			type: String,
+			default: "/"
```
Comment (greatislander) [inline components/Post.vue]: Is it possible to omit the default?

File: components/Post.vue [hunk 3]
```diff
@@ -68,7 +82,8 @@ figure {
   width: 100%; /* Set a small width */
   height: 60%;
   display: inline-block;
-  background-position: top;
+  /* background-position: top; */
```
Comment (greatislander) [inline components/Post.vue]: Can you remove the commented-out style?

Comment (TeddTech) [reply components/Post.vue]: Okay, will do

File: components/Post.vue [hunk 4]
```diff
@@ -68,7 +82,7 @@ figure {
   width: 100%; /* Set a small width */
   height: 60%;
   display: inline-block;
-  background-position: top;
+  background-size: cover;
```
Comment (jobara) [inline components/Post.vue]: Was this change intended to be included in this PR?

File: components/Post.vue (hunk 2 above)
Comment (TeddTech) [reply components/Post.vue]: Testing reply

File: components/Post.vue (hunk 4 above)
Comment (jobara) [reply components/Post.vue]: @TeddTech and I talked a bit more about this on a call. The reason is to better display/position the images used for search results and news items. 

The way items appear in master
Screen Shot 2020-02-05 at 1 27 52 PM

However, because this is a separate issue to what is mentioned in https://github.com/inclusive-design/wecount.inclusivedesign.ca/issues/10 I'm requesting that it be removed from this PR and filed as a new Issue.

File: components/Post.vue (hunk 2 above)
Comment (TeddTech) [reply components/Post.vue]: Not providing the defaults trigger `vue/require-default-prop` WARNING messages. An explanation of this rule can be found [here](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/require-default-prop.md)

File: components/Post.vue (hunk 4 above)
Comment (TeddTech) [reply components/Post.vue]: I have filed a new issue relating to this problem at Query Images #34 The PR is also up at #35

Comment (greatislander) [inline components/Post.vue]: @TeddTech I think as per @jobara's comment you should also remove this change from this PR as it is now addressed by #35.

Comment (TeddTech) [reply components/Post.vue]: This change has been completed
